language: node_js
node_js:
  - 0.12

env:
  - PHANTOMJS1=1.9.7
  - PHANTOMJS2=2.0.0

before_script:
  - "if [ -z \"$PHANTOMJS1\" ]; then wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2 -O - | tar -xj fi"
  - "if [ -z \"$PHANTOMJS1\" ]; then mv phantomjs-1.9.7-linux-x86_64/bin/phantomjs . fi"
  - "if [ -z \"$PHANTOMJS2\" ]; then wget https://github.com/bprodoehl/phantomjs/releases/download/2.0.0-20141016/phantomjs-2.0.0-20141016-u1410-x86_64.zip fi"
  - "if [ -z \"$PHANTOMJS2\" ]; then unzip -j phantomjs-2.0.0-20141016-u1410-x86_64.zip phantomjs-2.0.0-20141016/bin/phantomjs -d . fi"

script: npm test
